package today.learnslovak.first.domain.model;

public enum Pref implements Preferences {

  INSTALL_ID, LAST_SYNC,
  AVAILABLE_LANGS, LANG0, LANG1, LANG2, LANG3, LANG_SEARCH,
  SHOW_TRANS, SHOW_LANG2, HIDE_LEARNED,
  SNIPPETS_LIMIT, WORDS_LIMIT, EMAIL,
  WORD_EXT_LAST_ID, WORDS_LAST_ID,
  SKIP_IDS, LANG0_SKIP_IDS, LANG1_SKIP_IDS, LANG2_SKIP_IDS, LANG3_SKIP_IDS
}
